### ISSUE TITLE
VCS

### ISSUE THREAD

**Issue by DevanshuSyk** [alexbasista/terraform-tfe-workspacer#17]
Error while updating VCS repo

Error: Error updating workspace ws-Mg74zQMLm5uM6o4n: unprocessable entity OAuth token does not exist
with module.ccoe_workspace_1.tfe_workspace.ws
on .terraform/modules/ccoe_workspace_1/workspace.tf line 1, in resource "tfe_workspace" "ws":
resource "tfe_workspace" "ws" {

The token has access to all repo and has been configured to use SSO

**Comment by alexbasista** [comment]
Hi @DevanshuSyk would you mind sending a sanitized snippet of your code and the value of the OAuth Token ID?

**Comment by DevanshuSyk** [comment]
Thanxk for the reply @alexbasista  here is the snippet

main.tf
  vcs_repo = {
    identifier     = "<Org>/<repo>/tfc-azure-lz-subcriptionvending"
    branch         = "main"
    oauth_token_id = var.oauth_token_id
    tags_regex     = null # conflicts with `trigger_prefixes` and `trigger_patterns`
  }
  
  variable,tf
  variable "oauth_token_id" {
 type      = string
 sensitive = true
default= "ghp_iOxhOmkdFVhsSbv9gpwJBvr4k2mzL7q"
}

the oauth has been changed.

Thankx
Devanshu

**Comment by alexbasista** [comment]
That OAuth Token ID value doesn't look like a valid format.  It should be prefixed with `ot-` and look something like `ot-****************`.  You can get that value from the VCS provider config within your Organization-level settings.
